apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
      - name: api-conversao
        image: rfabricio/apiconv:2.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "400m"
          requests:
            cpu: "200m"
            memory: "32Mi"
        ports:
        - name: web-port
          containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: web-port
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: web-port
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-conversao
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-conversao
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer